### PR TITLE
Added two sites.

### PR DESCRIPTION
**Pull request by w32zhong**

### CODE REVIEW

**Comment by xiaoyu2er** [comment]
@t-k- these sites may be blocked, please check it again. If it will work, let me know, and i will merge.

**Comment by w32zhong** [comment]
Sorry for not working well, I actually checked it before I sent you request, but I was outside of China, which may be the problem. :disappointed:

**Comment by xiaoyu2er** [comment]
@t-k- don't worry. If you have other mirrors, glad to know. ( Do you really need this module....

**Comment by w32zhong** [comment]
@xiaoyu2er  helping others does not mean you need something :P

**Pull request closed without merging**
